/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_swirldb_free: (a: number, b: number) => void;
export const swirldb_new: () => number;
export const swirldb_withLocalStorage: (a: number, b: number) => any;
export const swirldb_withIndexedDB: (a: number, b: number) => any;
export const swirldb_setPath: (a: number, b: number, c: number, d: any) => [number, number];
export const swirldb_getPath: (a: number, b: number, c: number) => any;
export const swirldb_setValue: (a: number, b: number, c: number, d: any) => [number, number];
export const swirldb_getValue: (a: number, b: number, c: number) => any;
export const swirldb_getRootKeys: (a: number) => [number, number];
export const swirldb_saveState: (a: number) => any;
export const swirldb_loadState: (a: number, b: any) => [number, number];
export const swirldb_applyChanges: (a: number, b: number, c: number) => [number, number];
export const swirldb_getChanges: (a: number) => [number, number];
export const swirldb_getChangesSince: (a: number, b: number, c: number) => [number, number];
export const swirldb_getHeads: (a: number) => any;
export const swirldb_getHeadsArray: (a: number) => [number, number];
export const swirldb_observe: (a: number, b: number, c: number, d: any) => [number, number];
export const swirldb_enableAutoPersist: (a: number) => void;
export const swirldb_loadPolicyConfig: (a: number, b: number, c: number) => [number, number];
export const swirldb_withPolicy: (a: number, b: number) => [number, number, number];
export const swirldb_authenticateJWT: (a: number, b: number, c: number) => [number, number];
export const swirldb_getActor: (a: number) => any;
export const swirldb_persist: (a: number) => any;
export const swirldb_checkObservers: (a: number) => void;
export const swirldb_connect: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const swirldb_syncChanges: (a: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h9a932ac99699e6ea: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__h09128478747f473b: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h391af020e6f42ee5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__hd034537d4d4dd52d: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h7c0d50c30086be17: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_start: () => void;
